name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: Install python version 3.12
        uses: actions/steup-python@v5
        with:
          python-version: "3.12"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip insta -r requirements.txt
